/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import com.etospheres.etopay.ETOPaySdk;

public class App {
    public String getBuildInfo() {
		ETOPaySdk w = new ETOPaySdk();
		try {
			return w.getBuildInfo();
		} catch (Exception e ){
			e.printStackTrace();
			return null;
		}
    }

    public static void main(String[] args) throws Exception{
		App app = new App();
        System.out.println(app.getBuildInfo());
    }
}
